export const AntiSocialBehaviour = [
  "anti-social behaviour",
  "ASBO",
  "distress",
  "arson",
  "begging",
  "urinating in public",
  "drunk",
  "spitting",
  "paan",
  "urinating",
  "anti mask"
];

export const Theft = [
  "burglary",
  "breaking and entering",
  "housebreaking",
  "thief",
  "trespass property",
  "steal",
  "home invasion",
  "nick property",
  "burgle",
  "burglaries",
  "stole",
  "theft",
  "nicked",
  "stolen",
  "mugged",
  "pickpocket",
  "snatched",
  "theft from the person",
  "thieving",
  "stealing",
  "stole",
  "filching",
  "taking property",
  "handbag taken",
  "shoplift",
  "shoplifting",
  "five finger discount",
  "shoplifter",
  "stealing",
  "nicked from shop",
  "take without paying",
  "stolen goods",
  "stole",
  "thief",
  "lifting",
  "robbery",
  "armed robbery",
  "highway robbery",
  "aggravated robbery",
  "steal",
  "blagging",
  "stick-up",
  "violent theft",
  "mugging",
];
export const CriminalDamage = [
  "vandalism",
  "vandalised",
  "vandal",
  "arson",
  "graffiti",
  "deliberate damage",
  "malicious",
  "set fire",
  "criminal damage",
  "destroyed",
  "damaged",
  "keying car",
  "reckless",
];

export const DrugOffences = [
  "drugs",
  "drug possession",
  "intent to supply",
  "cannabis",
  "class a",
  "class b",
  "class c",
  "drug trafficking",
  "heroin",
  "cocaine",
  "LSD",
  "amphetamine",
  "ketamine",
  "ganja",
  "marijuana",
  "trafficking"
];

export const PossessionOfWeapons = [
  "weapon",
  "firearm",
  "possession weapon",
  "bomb",
  "artillery",
  "gun",
  "knife",
];

export const PublicOrder = [
  "public order",
  "riot",
  "lashing out",
  "fight",
  "abusive",
  "violent disorder",
  "affray",
  "harassment",
  "protest",
  "trespass",
  "racial",
  "racist",
  "religious hatred",
  "hate speech"
];

export const VehicleCrime = [
  "car jacking",
  "vehicle crime",
  "stolen car",
  "car nicked",
  "vehicle trafficking",
  "car theft",
  "car broken",
  "getaway vehicle",
  "getaway car",
  "car thief",
  "car crime",
  "car damaged",
  "stole motorbike",
  "taking driving away",
  "twockers",
  "twocking",
  "grand theft auto",
  "carjacking",
  "taken without owner's consent",
  "hotwire",
  "hotwiring",
  "car alarm",
];

export const ViolentCrime = [
  "violence",
  "stabbed",
  "stabbing",
  "knife attack",
  "punched",
  "assault",
  "robbery",
  "assassination",
  "homicide",
  "wounding",
  "domestic violence",
  "mugging",
  "murder",
  "murdered",
  "killed",
  "kills",
  "manslaughter",
  "infanticide",
  "sexual assault",
  "rape",
  "drink driving",
  "drug driving",
  "GBH",
  "harassment",
  "stalking",
  "sharp-edged"
];
export const CyberCrime = [
  "phishing",
  "cyber stalk",
  "cyber crime",
  "extortion",
  "bioterrorism",
  "copyright infringement",
  "child porn",
  "ddos",
  "piracy",
  "pirating",
  "malware",
  "ransomware",
  "hackers",
  "hacking",
  "dark web",
  "silk road",
  "malicious"
];

export const Terrorism = [
  "terrorism",
  "terrorist",
  "isis",
  "al-qaida",
  "suicide bomber",
  "taliban",
  "naxal",
  "indian mujahideen",
  "maoist",
  "bomb"
];

export const NonCrime = [];

export const Categories = {
  AntiSocialBehaviour,
  Theft,
  CriminalDamage,
  DrugOffences,
  PossessionOfWeapons,
  PublicOrder,
  VehicleCrime,
  ViolentCrime,
  CyberCrime,
  Terrorism,
  NonCrime
};
