export const AntiSocialBehaviour = [
  "anti-social behaviour",
  "ASBO",
  "distress",
  "arson",
  "begging",
  "urinating in public",
  "drunk",
  "spitting",
];

export const BikeTheft = [
  "bike theft",
  "bike nicked",
  "bike stolen",
  "bicycle nicked",
  "bicycle stole",
  "bike gone",
  "stole bike",
  "bike lock",
  "stole cycle",
  "sucker pole",
  "bike thief",
  "bike",
];
export const Burglary = [
  "burglary",
  "breaking and entering",
  "housebreaking",
  "thief",
  "trespass property",
  "steal",
  "home invasion",
  "nick property",
  "burgle",
  "burglaries",
  "stole",
];
export const CriminalDamage = [
  "vandalism",
  "vandalised",
  "vandal",
  "arson",
  "graffiti",
  "deliberate damage",
  "malicious",
  "set fire",
  "criminal damage",
  "destroyed",
  "damaged",
  "keying car",
  "reckless",
];

export const DrugOffences = [
  "drugs",
  "drug possession",
  "intent to supply",
  "cannabis",
  "class a",
  "class b",
  "class c",
  "drug trafficking",
  "heroin",
  "cocaine",
  "LSD",
  "amphetamine",
  "ketamine",
];

export const PossessionOfWeapons = [
  "weapon",
  "firearm",
  "possession weapon",
  "bomb",
  "artillery",
  "gun",
  "knife",
];

export const PublicOrder = [
  "public order",
  "riot",
  "lashing out",
  "fight",
  "abusive",
  "violent disorder",
  "affray",
  "harassment",
  "protest",
  "trespass",
  "racial",
  "racist",
  "religious hatred",
];

export const Robbery = [
  "robbery",
  "threat",
  "armed robbery",
  "highway robbery",
  "aggravated robbery",
  "steal",
  "blagging",
  "stick-up",
  "violent theft",
  "mugging",
  "car jacking",
];

export const Shoplifting = [
  "shoplift",
  "shoplifting",
  "boosting",
  "five finger discount",
  "shoplifter",
  "stealing",
  "nicked from shop",
  "take without paying",
  "stolen goods",
  "stole",
  "thief",
  "lifting",
];

export const TheftFromThePerson = [
  "theft",
  "nicked",
  "stolen",
  "mugged",
  "pickpocket",
  "snatched",
  "theft from the person",
  "thieving",
  "stealing",
  "stole",
  "filching",
  "taking property",
  "handbag taken",
];

export const VehicleCrime = [
  "vehicle crime",
  "stolen car",
  "car nicked",
  "vehicle trafficking",
  "car theft",
  "car broken",
  "getaway vehicle",
  "getaway car",
  "car thief",
  "car crime",
  "car damaged",
  "stole motorbike",
  "taking driving away",
  "twockers",
  "twocking",
  "grand theft auto",
  "carjacking",
  "taken without owner's consent",
  "hotwire",
  "hotwiring",
  "car alarm",
];

export const ViolentCrime = [
  "violence",
  "stabbed",
  "stabbing",
  "knife attack",
  "punched",
  "assault",
  "robbery",
  "homicide",
  "wounding",
  "domestic violence",
  "mugging",
  "murder",
  "murdered",
  "killed",
  "manslaughter",
  "infanticide",
  "sexual assault",
  "rape",
  "drink driving",
  "drug driving",
  "GBH",
  "harassment",
  "stalking",
];

export const Other = [];

export const Categories = {
  AntiSocialBehaviour,
  BikeTheft,
  Burglary,
  CriminalDamage,
  DrugOffences,
  PossessionOfWeapons,
  PublicOrder,
  Robbery,
  Shoplifting,
  TheftFromThePerson,
  VehicleCrime,
  ViolentCrime,
  Other,
};
